services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    image: fe-portfolio:latest
    container_name: fe-portfolio
    env_file:
      - .env
    ports:
      - '3000:3000'         # host:container
    restart: unless-stopped
    expose:
      - "3000"
    networks: [web]

networks:
  web:
    external: true
